[[StateMachineDescriptions]]
Name = "publish_status"
Label = "Publish Status"
InitialState = "draft"

  [[StateMachineDescriptions.Events]]
  Name = "mark_as_edited"
  Label = "Mark as edited"
  Src = ["draft", "ready-to-publish"]
  Dst = "ready-to-publish"

  [[StateMachineDescriptions.Events]]
  Name = "publish"
  Label = "Publish"
  Src = ["draft", "ready-to-publish"]
  Dst = "published"

  [[StateMachineDescriptions.Events]]
  Name = "delete"
  Label = "Delete"
  Src = ["draft", "ready-to-publish", "published"]
  Dst = "deleted"

[[Tables]]
TableName = "blog"

  [[Tables.Columns]]
  Name = "title"
  DataType = "varchar(500)"
  ColumnType = "label"

  [[Tables.Columns]]
  Name = "view_count"
  DataType = "int(11)"
  ColumnType = "measurement"

[[Tables]]
TableName = "post"

  [[Tables.Columns]]
  Name = "title"
  DataType = "varchar(200)"
  ColumnType = "label"

  [[Tables.Columns]]
  Name = "body"
  DataType = "text"
  ColumnType = "content"

[[Tables]]
TableName = "comment"

  [[Tables.Columns]]
  Name = "body"
  DataType = "text"
  ColumnType = "content"

  [[Tables.Columns]]
  Name = "likes_count"
  ColumnName = "likes_count"
  DataType = "int(11)"
  ColumnType = "measurement"

[[Relations]]
Subject = "comment"
Relation = "belongs_to"
Object = "post"

[[Relations]]
Subject = "post"
Relation = "belongs_to"
Object = "blog"

[[Relations]]
Subject = "blog"
Relation = "has_one"
Object = "post"
ObjectName = "current_post"
SubjectName = "current_post_of"

[[Actions]]
Name = "comment"
Label = "Leave a comment"
OnType = "post"

  [[Actions.InFields]]
  ColumnName = "name"
  Name = "Author Name"
  ColumnType = "label"

  [[Actions.InFields]]
  ColumnName = "comment"
  Name = "Your comment"
  ColumnType = "content"

  [[Actions.InFields]]
  ColumnName = "like"
  Name = "Rating"
  ColumnType = "rating"

  [[Actions.OutFields]]
  Method = "POST"
  Type = "comment"

    [Actions.OutFields.Attributes]
    body = "~comment"
    post_id = "$.reference_id"
    likes_count = "~like"

[[Actions]]
Name = "post"
Label = "Create a new post"
OnType = "blog"

  [[Actions.InFields]]
  ColumnName = "title"
  Name = "Post title"
  ColumnType = "label"

  [[Actions.InFields]]
  ColumnName = "body"
  Name = "Blog"
  ColumnType = "content"

  [[Actions.OutFields]]
  Type = "post"
  Method = "POST"

    [Actions.OutFields.Attributes]
    title = "~title"
    body = "~body"
    blog_id = "$.reference_id"

[[Exchanges]]
Name = "Blog to excel sheet sync"
SourceType = "self"
TargetType = "gsheet-append"

  [Exchanges.SourceAttributes]
  Name = "blog"

  [Exchanges.TargetAttributes]
  sheetUrl = "https://content-sheets.googleapis.com/v4/spreadsheets/1Ru-bDk3AjQotQj72k8SyxoOs84eXA1Y6sSPumBb3WSA/values/A1:append"

  [Exchanges.Options]
  hasHeader = true

  [[Exchanges.Attributes]]
  sourceColumn = "$blog.title"
  targetColumn = "Blog title"

  [[Exchanges.Attributes]]
  sourceColumn = "$blog.view_count"
  targetColumn = "View count"
