[[Tables]]
TableName = "merchant"

  [[Tables.Columns]]
  Name = "name"
  ColumnName = "name"
  ColumnDescription = ""
  ColumnType = "label"
  IsPrimaryKey = false
  IsAutoIncrement = false
  IsIndexed = true
  IsUnique = false
  IsNullable = false
  DataType = "varchar(500)"

  [[Tables.Columns]]
  Name = "image_url"
  ColumnName = "image_url"
  ColumnDescription = ""
  ColumnType = "label"
  IsPrimaryKey = false
  IsAutoIncrement = false
  IsIndexed = false
  IsUnique = false
  DataType = "varchar(500)"

[[Tables]]
TableName = "integration"

  [[Tables.Columns]]
  Name = "description"
  ColumnName = "description"
  ColumnDescription = ""
  ColumnType = "content"
  IsNullable = true
  DataType = "text"

  [[Tables.Columns]]
  Name = "language"
  ColumnName = "language"
  ColumnType = "label"
  IsIndexed = true
  DataType = "varchar(100)"

  [[Tables.Columns]]
  Name = "api_sub_type"
  ColumnName = "api_sub_type"
  ColumnType = "label"
  IsPrimaryKey = false
  IsAutoIncrement = false
  IsIndexed = true
  IsUnique = false
  IsNullable = true
  DataType = "varchar(100)"

  [[Tables.Columns]]
  Name = "name"
  ColumnName = "name"
  ColumnDescription = ""
  ColumnType = "label"
  IsPrimaryKey = false
  IsAutoIncrement = false
  IsIndexed = true
  IsUnique = false
  IsNullable = false
  DataType = "varchar(100)"

  [[Tables.Columns]]
  Name = "stack"
  ColumnName = "stack"
  ColumnDescription = ""
  ColumnType = "label"
  IsPrimaryKey = false
  IsAutoIncrement = false
  IsIndexed = true
  IsUnique = false
  IsNullable = false
  DataType = "varchar(100)"

  [[Tables.Columns]]
  Name = "api_type"
  ColumnName = "api_type"
  ColumnDescription = ""
  ColumnType = "label"
  IsPrimaryKey = false
  IsAutoIncrement = false
  IsIndexed = true
  IsUnique = false
  IsNullable = true
  DataType = "varchar(100)"

  [[Tables.Columns]]
  Name = "change_set"
  ColumnName = "change_set"
  ColumnDescription = ""
  ColumnType = "json"
  IsPrimaryKey = false
  IsAutoIncrement = false
  IsIndexed = true
  IsUnique = false
  IsNullable = false
  DataType = "text"

  [[Tables.Columns]]
  Name = "icon"
  ColumnName = "icon"
  ColumnDescription = ""
  ColumnType = "label"
  IsPrimaryKey = false
  IsAutoIncrement = false
  IsIndexed = false
  IsUnique = false
  IsNullable = false
  DataType = "varchar(100)"
  DefaultValue = "'devicon-devicon-plain'"

  [[Tables.Columns]]
  Name = "color"
  ColumnName = "color"
  ColumnDescription = ""
  ColumnType = "color"
  IsPrimaryKey = false
  IsAutoIncrement = false
  IsIndexed = false
  IsUnique = false
  IsNullable = false
  DataType = "varchar(10)"
  DefaultValue = "'#708ad8'"

[[Relations]]
Subject = "integration"
Relation = "belongs_to"
Object = "merchant"
