Exchanges = []

[[Tables]]
TableName = "inventory"

  [[Tables.Columns]]
  Name = "name"
  DataType = "varchar(100)"
  ColumnType = "label"
  IsIndexed = true

  [[Tables.Columns]]
  Name = "description"
  DataType = "text"
  ColumnType = "label"

  [[Tables.Columns]]
  Name = "line_items"
  DataType = "int(11)"
  ColumnType = "measurement"

  [[Tables.Conformations]]
  ColumnName = "order"
  Tags = "numeric"

  [[Tables.Validations]]
  ColumnName = "title"
  Tags = "required"

[[Tables]]
TableName = "sale"

  [[Tables.Columns]]
  Name = "is_returned"
  DataType = "bool"
  ColumnType = "truefalse"
  DefaultValue = "0"

[[Relations]]
Subject = "inventory"
Relation = "has_many"
Object = "sale"

[[Actions]]
Name = "new_purchase"
Label = "Purchase"
OnType = "inventory"
InstanceOptional = false
InFields = []

  [[Actions.OutFields]]
  Type = "sale"
  Method = "POST"
  Reference = "sale"

    [Actions.OutFields.Attributes]

  [[Actions.OutFields]]
  Type = "inventory"
  Method = "UPDATE"

    [Actions.OutFields.Attributes]
    line_items = "!subject.line_items - 1"
    reference_id = "$.reference_id"

  [[Actions.OutFields]]
  Type = "inventory_inventory_id_has_sale_sale_id"
  Method = "POST"
  Reference = "inventory_sale"

    [Actions.OutFields.Attributes]
    sale_id = "$sale.reference_id"
    inventory_id = "$.reference_id"

  [[Actions.OutFields]]
  Type = "client.notify"
  Method = "ACTIONRESPONSE"

    [Actions.OutFields.Attributes]
    type = "success"
    message = "You have purchased a new item"
    title = "Wait for it"

  [[Actions.OutFields]]
  Type = "client.redirect"
  Method = "ACTIONRESPONSE"

    [Actions.OutFields.Attributes]
    location = "/in/item/sale/$sale.reference_id"
    window = "self"
    delay = "1000"

[[Actions]]
Name = "return"
Label = "Return item"
OnType = "sale"
InstanceOptional = false

  [[Actions.OutFields]]
  Type = "sale"
  Method = "UPDATE"

    [Actions.OutFields.Attributes]
    is_returned = "1"
    reference_id = "$.reference_id"
