[[StateMachineDescriptions]]
Name = "light_states"
Label = "Light status"
InitialState = "green"

  [[StateMachineDescriptions.Events]]
  Name = "warn"
  Label = "warn"
  Src = ["green"]
  Dst = "yellow"

  [[StateMachineDescriptions.Events]]
  Name = "panic"
  Label = "panic"
  Src = ["yellow", "green"]
  Dst = "red"

  [[StateMachineDescriptions.Events]]
  Name = "calm"
  Label = "calm"
  Src = ["red"]
  Dst = "yellow"

  [[StateMachineDescriptions.Events]]
  Name = "calm"
  Label = "calm"
  Src = ["yellow"]
  Dst = "green"

[[Tables]]
TableName = "style"

  [[Tables.Columns]]
  Name = "name"
  DataType = "varchar(500)"
  ColumnType = "label"

  [[Tables.Columns]]
  Name = "code"
  DataType = "varchar(100)"
  ColumnType = "label"
  IsUnique = true

[[Tables]]
TableName = "orders"

  [[Tables.Columns]]
  Name = "quantity"
  DataType = "int(11)"
  ColumnType = "measurement"

[[Tables]]
TableName = "vendor"

  [[Tables.Columns]]
  Name = "name"
  ColumnType = "label"
  DataType = "varchar(100)"

[[Tables]]
TableName = "cost"

  [[Tables.Columns]]
  Name = "pre_road_show_cost"
  DataType = "int(11)"
  ColumnType = "measurement"

  [[Tables.Columns]]
  Name = "Target_cost"
  DataType = "int(11)"
  ColumnType = "measurement"

  [[Tables.Columns]]
  Name = "post_road_show_cost"
  DataType = "int(11)"
  ColumnType = "measurement"

[[Tables]]
TableName = "style_file"

  [[Tables.Columns]]
  Name = "color"
  DataType = "varchar(100)"
  ColumnType = "color"

[[Relations]]
Subject = "cost"
Relation = "belongs_to"
Object = "style"

[[Relations]]
Subject = "style"
Relation = "has_one"
Object = "style_file"

[[Relations]]
Subject = "style"
Relation = "has_many"
Object = "orders"

[[Relations]]
Subject = "orders"
Relation = "has_one"
Object = "vendor"

[[Actions]]
Name = "new_order"
Label = "Create a new order for the style"
OnType = "style"

  [[Actions.InFields]]
  ColumnName = "vendor"
  Name = "Vendor"
  ColumnType = "vendor"

  [[Actions.InFields]]
  ColumnName = "quantity"
  Name = "quantity"
  ColumnType = "measurement"

  [[Actions.OutFields]]
  Type = "vendor"
  Method = "POST"
  Reference = "vendor1"

    [Actions.OutFields.Attributes]
    name = "~vendor"

  [[Actions.OutFields]]
  Type = "orders"
  Method = "POST"
  Reference = "order1"

    [Actions.OutFields.Attributes]
    vendor_id = "$vendor1.reference_id"
    quantity = "~quantity"

  [[Actions.OutFields]]
  Type = "style_style_id_has_orders_orders_id"
  Method = "POST"

    [Actions.OutFields.Attributes]
    orders_id = "$order1.reference_id"
    style_id = "$.reference_id"

[[Exchanges]]
Name = "Style to excel sync"
SourceType = "self"
TargetType = "gsheet-append"

  [Exchanges.SourceAttributes]
  Name = "style"

  [Exchanges.TargetAttributes]
  sheetUrl = "https://content-sheets.googleapis.com/v4/spreadsheets/1Ru-bDk3AjQotQj72k8SyxoOs84eXA1Y6sSPumBb3WSA/values/A1:append"

  [Exchanges.Options]
  hasHeader = true

  [[Exchanges.Attributes]]
  SourceColumn = "$style.title"
  TargetColumn = "Style title"

[[Exchanges]]
Name = "Order to excel sync"
SourceType = "self"
TargetType = "gsheet-append"
Attributes = []

  [Exchanges.SourceAttributes]
  Name = "orders"

  [Exchanges.TargetAttributes]
  sheetUrl = "https://content-sheets.googleapis.com/v4/spreadsheets/1Ru-bDk3AjQotQj72k8SyxoOs84eXA1Y6sSPumBb3WSA/values/A1:append"

  [Exchanges.Options]
  hasHeader = true

[[Exchanges]]
Name = "Vendor to excel sync"
SourceType = "self"
TargetType = "gsheet-append"
Attributes = []

  [Exchanges.SourceAttributes]
  Name = "vendor"

  [Exchanges.TargetAttributes]
  sheetUrl = "https://content-sheets.googleapis.com/v4/spreadsheets/1Ru-bDk3AjQotQj72k8SyxoOs84eXA1Y6sSPumBb3WSA/values/A1:append"

  [Exchanges.Options]
  hasHeader = true
