[[StateMachineDescriptions]]
Name = "task_status"
Label = "Task Status"
InitialState = "to_be_done"

  [[StateMachineDescriptions.Events]]
  Name = "start"
  Label = "Start"
  Src = ["to_be_done", "delayed"]
  Dst = "started"

  [[StateMachineDescriptions.Events]]
  Name = "delayed"
  Label = "Unable to pick up"
  Src = ["to_be_done"]
  Dst = "delayed"

  [[StateMachineDescriptions.Events]]
  Name = "ongoing"
  Label = "Record progress"
  Src = ["started", "ongoing"]
  Dst = "ongoing"

  [[StateMachineDescriptions.Events]]
  Name = "interrupted"
  Label = "Interrupted"
  Src = ["started", "ongoing"]
  Dst = "interrupted"

  [[StateMachineDescriptions.Events]]
  Name = "resume"
  Label = "Resume from interruption"
  Src = ["interrupted"]
  Dst = "ongoing"

  [[StateMachineDescriptions.Events]]
  Name = "completed"
  Label = "Mark as completed"
  Src = ["ongoing", "started"]
  Dst = "completed"

[[Tables]]
TableName = "todo"

  [[Tables.Columns]]
  Name = "title"
  DataType = "varchar(500)"
  ColumnType = "label"
  IsIndexed = true

  [[Tables.Columns]]
  Name = "url"
  DataType = "varchar(200)"
  ColumnType = "url"
  IsNullable = true

  [[Tables.Columns]]
  Name = "completed"
  DataType = "int(1)"
  ColumnType = "truefalse"
  DefaultValue = "false"

  [[Tables.Columns]]
  Name = "schedule"
  DataType = "date"
  ColumnType = "date"
  IsNullable = true

  [[Tables.Columns]]
  Name = "order"
  columnName = "item_order"
  DataType = "int(4)"
  ColumnType = "measurement"
  DefaultValue = "10"

  [[Tables.Columns]]
  Name = "text"
  DataType = "text"
  ColumnType = "content"
  IsNullable = true

  [[Tables.Conformations]]
  ColumnName = "order"
  Tags = "numeric"

  [[Tables.validations]]
  ColumnName = "title"
  Tags = "required"

[[Tables]]
TableName = "tag"

  [[Tables.Columns]]
  Name = "label"
  DataType = "varchar(100)"
  ColumnType = "label"
  IsIndexed = true

[[Tables]]
TableName = "project"

  [[Tables.Columns]]
  Name = "name"
  DataType = "varchar(200)"
  ColumnType = "name"
  IsIndexed = true

[[Relations]]
Subject = "todo"
Relation = "has_one"
Object = "project"

[[Relations]]
Subject = "todo"
Relation = "has_many"
Object = "tag"

[[Actions]]
Name = "new_task"
Label = "New to do"
OnType = "project"
InstanceOptional = true

  [[Actions.InFields]]
  ColumnName = "description"
  Name = "Description"
  ColumnType = "label"

  [[Actions.InFields]]
  ColumnName = "schedule"
  Name = "Scheduled at"
  ColumnType = "date"

  [[Actions.OutFields]]
  Type = "todo"
  Method = "POST"

    [Actions.OutFields.Attributes]
    schedule = "~schedule"
    title = "~description"
    project_id = "$.reference_id"

  [[Actions.OutFields]]
  Type = "client.notify"
  Method = "ACTIONRESPONSE"

    [Actions.OutFields.Attributes]
    type = "success"
    message = "Created new todo, taking you to it."
    title = "Wait for it"

  [[Actions.OutFields]]
  Type = "client.redirect"
  Method = "ACTIONRESPONSE"

    [Actions.OutFields.Attributes]
    location = "/in/item/todo/$.reference_id"
    window = "self"
    delay = "1000"

  [[Actions.OutFields]]
  Type = "client.store.set"
  Method = "ACTIONRESPONSE"

    [Actions.OutFields.Attributes]
    value = "last_created_todo"
    key = "$.reference_id"

  [[Actions.OutFields]]
  Type = "error"
  Method = "ACTIONRESPONSE"

    [Actions.OutFields.Attributes]
    message = "show this in error notification body"

[[Actions]]
Name = "completed"
Label = "Completed"
OnType = "todo"

  [[Actions.OutFields]]
  Type = "todo"
  Method = "UPDATE"

    [Actions.OutFields.Attributes]
    completed = "1"
    reference_id = "$.reference_id"

[[Actions]]
Name = "new_project"
Label = "New project category"
OnType = "project"
InstanceOptional = true

  [[Actions.InFields]]
  ColumnName = "name"
  Name = "name"
  ColumnType = "label"

  [[Actions.OutFields]]
  Type = "project"
  Method = "POST"

    [Actions.OutFields.Attributes]
    name = "~name"

  [[Actions.OutFields]]
  Type = "client.redirect"
  Method = "ACTIONRESPONSE"

    [Actions.OutFields.Attributes]
    location = "/in/item/project/$.reference_id"
    window = "self"
    delay = "1000"

[[Actions]]
Name = "new_data_exchange"
Label = "Sync tasks to Google sheet"
OnType = "data_exchange"

  [[Actions.InFields]]
  ColumnName = "sheetUrl"
  Name = "Sheet url"
  ColumnType = "url"

  [[Actions.InFields]]
  ColumnName = "include_all_columns"
  Name = "Include all Columns ?"
  ColumnType = "boolean"
  DefaultValue = "false"

  [[Actions.OutFields]]
  Type = "data_exchange"
  Method = "POST"

    [Actions.OutFields.Attributes]
    schedule = "~schedule"
    description = "~description"
    project_id = "$.reference_id"

[[Exchanges]]
Name = "Task to excel sheet"
SourceType = "self"
TargetType = "gsheet-append"

  [Exchanges.SourceAttributes]
  Name = "todo"

  [Exchanges.TargetAttributes]
  sheetUrl = "https://content-sheets.googleapis.com/v4/spreadsheets/1Ru-bDk3AjQotQj72k8SyxoOs84eXA1Y6sSPumBb3WSA/values/A1:append"
  appKey = "AIzaSyAC2xame4NShrzH9ZJeEpWT5GkySooa0XM"

  [Exchanges.Options]
  hasHeader = true

  [[Exchanges.Attributes]]
  SourceColumn = "$self.description"
  TargetColumn = "Task description"

  [[Exchanges.Attributes]]
  SourceColumn = "self.schedule"
  TargetColumn = "Scheduled at"
